name: defiende-la-torre
version: 0.1.0.0
license: MIT
author: "Mauricio"
extra-source-files: []

library:
  source-dirs: src
  exposed-modules: []
  ghc-options: -Wall
  default-language: Haskell2010
  dependencies:
    - base >= 4.7 && < 5
    - aeson
    - bytestring
    - containers
    - random
    - text

executables:
  defiende:
    main: Main.hs
    source-dirs: src
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    default-language: Haskell2010
    dependencies:
      - base >= 4.7 && < 5
      - aeson
      - bytestring
      - containers
      - random
      - text
